Fix unallowed reinterpret_cast
See note at ¶5.2.10, bullet 9, of the n3797 C++ draft:

"A null pointer constant of type std::nullptr_t cannot be converted to a
pointer type, and a null pointer constant of integral type is not
necessarily converted to a null pointer value."

This addresses the following clang90 errors:

```
../include/reflex/matcher.h:142:42: error: reinterpret_cast from 'nullptr_t' to 'const char *' is not allowed
    return std::pair<const char*,size_t>(reinterpret_cast<const char*>(NULL), 0);
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/reflex/matcher.h:148:52: error: reinterpret_cast from 'nullptr_t' to 'const char *' is not allowed
    return std::pair<size_t,const char*>(accept(), reinterpret_cast<const char*>(NULL));
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/reflex/matcher.h:154:45: error: reinterpret_cast from 'nullptr_t' to 'const char *' is not allowed
    return std::pair<size_t,const char*>(0, reinterpret_cast<const char*>(NULL));
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pattern.cpp:2068:60: error: reinterpret_cast from 'nullptr_t' to 'DFA::State *' is not allowed
      state->edges[hi] = std::pair<Char,DFA::State*>(0xFF, reinterpret_cast<DFA::State*>(NULL));
                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```